services:
  hamariinfo:
    build: .
    container_name: hamariinfo
    restart: always
    env_file: .env
    ports:
      - "3000"  
    volumes:
      - /var/www/hamariinfo/media:/app/public/media      
    networks:
      - global

networks:
  global:
    external: true


